### ISSUE TITLE
[Question] About blocking selenium,puppeteer,playwright, scrapy bot

### ISSUE THREAD

**Issue by thomasmuus** [moskrc/crawlerdetect#4]
Hi, it seems like when I try to use this by wrapping it via API so that I can detect any automatic scraper like selenium,puppeteer,playwright, scrapy, it is unable to detect it. 

How can we make it detect all the scraper generated by selenium,puppeteer,playwright, scrapy and any other bot specially which can be scraping information ?

**Comment by moskrc** [comment]
Could you send an example, please?

**Comment by reese-allison** [comment]
> Hi, it seems like when I try to use this by wrapping it via API so that I can detect any automatic scraper like selenium,puppeteer,playwright, scrapy, it is unable to detect it.
> 
> How can we make it detect all the scraper generated by selenium,puppeteer,playwright, scrapy and any other bot specially which can be scraping information ?

I know this question is years old at this point. Those scrapers you are asking about usually pilot a headless browser instance. In such a case, the UserAgent present would likely match whatever the headless browser's UserAgent typically is. For example, the default for selenium and puppeteer is usually headless chrome, meaning the `HeadlessChrome` condition in `crawlerdetect` would pick it up. If the UserAgent is left blank or is manually changed such that it no longer looks like a bot, then this package wouldn't be able to pick it up.

@moskrc, I think you can probably close this :)
