### ISSUE TITLE
Add version number method to CrawlerDetect()

### ISSUE THREAD

**Issue by Mjboothaus** [moskrc/crawlerdetect#7]
It would be nice to be able to easily return the package version number (so that the status of a crawler can be version-stamped). Cheers! :)

**Comment by moskrc** [comment]
@Mjboothaus could you write an example, please? How do you want to use it?

**Comment by Mjboothaus** [comment]
Hi Vitalii - thanks for your prompt reply.

What I am trying to achieve is the following:
- The list of known crawlers changes through time
- Therefore as well as looking up if the user_agent identifier is a crawler or not, I would like to record the version of the code that produced this result i.e. something may not be a known crawler at a point in time and then is later identified as such.

I hope this makes sense. 

So for example: 

Crawler name                       User Agent ID                                   CrawlerDetect version
`Go-http-client`                    `Go-http-client/1.1,gzip(gfe)`       0.1.5

`crawler_detect.isCrawler(user_agent).getMatches()`

maybe also have a method like:

`crawler_detect.version()`

Although I think there is the package_version and also a database_version (of known crawlers) - the later is probably more useful.

I noticed that you do have a `get_crawlerdetect_version()` in `__main.py__` however I don't think this is exposed? (Apologies if I have missed something).

**Comment by moskrc** [comment]
@Mjboothaus I apologize for the delayed response. The 'version' property was added today by @reese-allison ([commit link](https://github.com/moskrc/crawlerdetect/pull/12/commits/9e5c917992142a6670201482ec3b56456e941275#diff-87d216fa8a44947111fb889cb5a8d21c929d2a1daf42eef7159f06a9208b9883R37)). It displays the package version.

In the near future, I plan to add a script to synchronize with the PHP version and provide more detailed version information. This will improve clarity regarding the database's relevance and update status.

**Comment by moskrc** [comment]
Added 'version' property
```python
from crawlerdetect import CrawlerDetect
crawler_detect = CrawlerDetect()
crawler_detect.version
```
