### ISSUE TITLE
Found an unfiltered crawler MonSpark

### ISSUE THREAD

**Issue by Bharath11031999** [moskrc/crawlerdetect#9]
I came across a crawler which was not filtered. The browser agent is listed below:
Mozilla/5.0+(compatible; MonSpark/1.0; http://www.monspark.com/)

**Comment by reese-allison** [comment]
I think this can be closed now that you merged his PR @moskrc.
Though I would recommend adding 
`Mozilla/5.0+(compatible; MonSpark/1.0; http://www.monspark.com/)` 
to the tests as his PR didn't include it.
